### ISSUE TITLE
Мигрировать вики из старого репозитория

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rust_book_ru#2]

**Comment by Vinatorul** [comment]
Почему-то при попытке зайти в `wiki` редиректит на основную страницу репозитория.

**Comment by mkpankov** [comment]
Здесь или у kgv?

**Comment by Vinatorul** [comment]
Здесь https://github.com/ruRust/rust_book_ru/wiki 
Будто отключено в настройках проекта.

**Comment by mkpankov** [comment]
Теперь должно показываться.

**Comment by Vinatorul** [comment]
А ну я всё равно не могу там ничего править. Действительно.

**Comment by mkpankov** [comment]
@Vinatorul теперь у тебя должен быть доступ

**Comment by mkpankov** [comment]
Оказывается это тоже git-репозиторий. Я его к нам мигрировал.
