### ISSUE TITLE
Добавить в словарь терминов каноничный перевод "borrow checker"

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rust_book_ru#21]

**Comment by kstep** [comment]
А такой вообще есть? Я бы предложил что-то вроде «шаг (компилятора) проверки заимствований».

**Comment by ozkriff** [comment]
"анализатор заимствований"?

**Comment by kstep** [comment]
ИМХО проблема в том, что просто «проверка заимствований» не подходит, так как описывает процесс, а не устройство, которое осуществляет процесс (как это делает английская фраза). Может быть ещё «система проверки заимствований»?

**Comment by kstep** [comment]
Да, наиболее похоже на правду.
25 янв. 2016 г. 11:44 AM пользователь Andrey Lesnikov <notifications@github.com> написал:"анализатор заимствований"?

**Comment by mkpankov** [comment]
Добавил "анализатор заимствований".
