### ISSUE TITLE
Сделать редирект с предыдущего репозитория

### ISSUE THREAD

**Issue by D101101** [ruRust/rust_book_ru#22]
Сделать редирект с http://kgv.github.io/rust_book_ru/ на http://rurust.github.io/rust_book_ru/

**Comment by mkpankov** [comment]
Это было бы хорошо, но как?

**Comment by defuz** [comment]
Как вариант, можно на все страницы в gh-pages добавить такой тег:

```html
<meta http-equiv=refresh content=0;url=http://rurust.github.io/rust_book_ru/src/[...].html>
```

**Comment by mkpankov** [comment]
@defuz а теперь подумалось - даже если это будет работать, похоже на hijacking какой-то

**Comment by defuz** [comment]
@mkpankov Гугл вроде бы адекватно к таким вещам относится, понимая, что это единственный способ сделать редирект там, где есть возможность редактировать только контент страницы, но не заголовки.

**Comment by mkpankov** [comment]
Давайте попробуем.

@D101101 сможешь впилить? У тебя вроде должен быть доступ на запись в старый репозиторий.

**Comment by defuz** [comment]
@mkpankov @D101101 Раз такое дело, рекомендую также вставлять:

```rust
<link rel="canonical" href="http://rurust.github.io/rust_book_ru/src/[...].html" />
```

Это укажет Google, что новые страницы являются "каноничными", а старые – "копиями", так что поисковый вес будет перетекать на новый адрес.

**Comment by D101101** [comment]
@defuz т.е. нужно обе строчки вставлять? порядок важен?

**Comment by mkpankov** [comment]
Надо ещё написать в README, что это мы редикерты установили, чтобы народ не пугался. И можно закрывать.

**Comment by mkpankov** [comment]
Решили не писать ничего, и так понятно. Закрываю.
