### ISSUE TITLE
Кнопка toggle_nav не открывает боковую панель

### ISSUE THREAD

**Issue by kefirchik** [ruRust/rust_book_ru#28]
Нет возможности открыть боковое меню в онлайн версии книги при размере окна менее 1060px

**Comment by kefirchik** [comment]
upd: не работает в разделах rust_book_ru/src

**Comment by mevsme** [comment]
А, я наверное не туда Issue запостил. Там все закрыты были, не внимательно посмотрел *shy*

**Comment by mkpankov** [comment]
Исправлено в https://github.com/ruRust/rust_book_ru/commit/60fcb56076fb7c4a7bfd61dd5ae36f154ce45fa0
