### ISSUE TITLE
src/getting-started.md ошибка в слове «выберите»

### ISSUE THREAD

**Issue by 0niichan** [ruRust/rust_book_ru#29]
В файле **src/getting-started.md**

172: «снова, _выберете_ "Change" на странице "Change, repair, or remove installation" и»
стоит поменять на
172: «снова, _выберите_ "Change" на странице "Change, repair, or remove installation" и»

**Comment by edubenetskiy** [comment]
Было исправлено в #36, полагаю, можно закрыть.
