### ISSUE TITLE
Синхранизация книги с Rust 1.6 stable

### ISSUE THREAD

**Issue by vessd** [ruRust/rust_book_ru#3]
- [x] Getting Started
- [x] Learn Rust
  - [x] Guessing Game
  - [x] Dining Philosophers
  - [x] Rust Inside Other Languages
- [x] Syntax and Semantics
  - [x] Variable Bindings
  - [x] Functions
  - [x] Primitive Types
  - [ ] Comments
  - [ ] if
  - [ ] Loops
  - [ ] Ownership
  - [ ] References and Borrowing
  - [ ] Lifetimes
  - [ ] Mutability
  - [ ] Structs
  - [ ] Enums
  - [ ] Match
  - [ ] Patterns
  - [ ] Method Syntax
  - [ ] Vectors
  - [ ] Strings
  - [ ] Generics
  - [ ] Traits
  - [ ] Drop
  - [ ] if let
  - [ ] Trait Objects
  - [ ] Closures
  - [ ] Universal Function Call Syntax
  - [ ] Crates and Modules
  - [ ] `const` and `static`
  - [ ] Attributes
  - [ ] `type` aliases
  - [ ] Casting between types
  - [ ] Associated Types
  - [ ] Unsized Types
  - [ ] Operators and Overloading
  - [ ] Deref coercions
  - [ ] Macros
  - [ ] Raw Pointers
  - [ ] `unsafe`
- [ ] Effective Rust
  - [ ] The Stack and the Heap
  - [ ] Testing
  - [ ] Conditional Compilation
  - [ ] Documentation
  - [ ] Iterators
  - [ ] Concurrency
  - [ ] Error Handling
  - [ ] Choosing your Guarantees
  - [ ] FFI
  - [ ] Borrow and AsRef
  - [ ] Release Channels
  - [ ] Using Rust without the standard library
- [ ] Nightly Rust
  - [ ] Compiler Plugins
  - [ ] Inline Assembly
  - [ ] No stdlib
  - [ ] Intrinsics
  - [ ] Lang items
  - [ ] Advanced linking
  - [ ] Benchmark Tests
  - [ ] Box Syntax and Patterns
  - [ ] Slice Patterns
  - [ ] Associated Constants
  - [ ] Custom Allocators
- [ ] Glossary
- [ ] Syntax Index
- [ ] Bibliography

**Comment by Gordon-F** [comment]
@vessd @mkpankov Книга в данный момент только в статусе поддержки ? Или синхронизация все же планируется ?

**Comment by vessd** [comment]
@Gordon-F В то время у меня появились более важные дела и не было возможности этим заниматься. Сейчас я не уверен, что готов заниматься синхронизацией. Тем более вторая версия книги выглядит уже достаточно внушительно и возможно даже стоит начать её переводить.

**Comment by Gordon-F** [comment]
@vessd На мой взгляд до версии 1.0 переводить ее не стоит. Она слишком активно меняется, на мой взгляд.

Так же считаю, что синхронизация уже бессмысленна. Лучше будет сосредоточится в дальнейшем на переводе новой книги.

**Comment by mkpankov** [comment]
@Gordon-F @vessd как писал [в планах](https://rustycrate.ru/%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8/2017/01/28/rustycrate-plans-2017-part1.html#knighi), предлагаю остановить эту деятельность и сосредоточиться на "Расте на примерах". Когда выйдет новая книга, займёмся ей.
