### ISSUE TITLE
src/getting-started.md ошибка в слове «наподобие»

### ISSUE THREAD

**Issue by 0niichan** [ruRust/rust_book_ru#30]
В файле **src/getting-started.md**

401: «ошибке _на подобии_ "`команда не найдена`", то вам нужно ознакомится с»
стоит поменять на
401: «ошибке _наподобие_ "`команда не найдена`", то вам нужно ознакомится с»

**Comment by edubenetskiy** [comment]
Было исправлено в #36, полагаю, можно закрыть.
