### ISSUE TITLE
src/getting-started.md ошибка в слове «ознакомиться»

### ISSUE THREAD

**Issue by 0niichan** [ruRust/rust_book_ru#31]
В файле **src/getting-started.md**

401: «ошибке наподобие "`команда не найдена`", то вам нужно _ознакомится_ с»
стоит поменять на
401: «ошибке наподобие "`команда не найдена`", то вам нужно _ознакомиться_ с»

**Comment by edubenetskiy** [comment]
Было исправлено в #36, думаю, можно закрыть.
