### ISSUE TITLE
src/getting-started.md пропущена запятая

### ISSUE THREAD

**Issue by 0niichan** [ruRust/rust_book_ru#32]
В файле **src/getting-started.md**

430: «нам сохранять наши проекты красивыми и аккуратными. Всему есть своё _место и_ все»
стоит поменять на
430: «нам сохранять наши проекты красивыми и аккуратными. Всему есть своё _место, и_ все»

**Comment by edubenetskiy** [comment]
Было исправлено в #36, думаю, можно закрыть.
