### ISSUE TITLE
src/getting-started.md пропущены запятые

### ISSUE THREAD

**Issue by 0niichan** [ruRust/rust_book_ru#33]
В файле **src/getting-started.md**

488: «Та-да! Мы собрали наш проект вызвав `cargo build` и запустили его с помощью»
стоит поменять на
488: «Та-да! Мы собрали наш проект_, вызвав `cargo build`,_ и запустили его с помощью»

**Comment by edubenetskiy** [comment]
Было исправлено в #36, полагаю, можно закрыть.
