### ISSUE TITLE
src/getting-started.md пропущена запятая

### ISSUE THREAD

**Issue by 0niichan** [ruRust/rust_book_ru#34]
В файле **src/getting-started.md**

489: «`./target/debug/hello_world`. Мы можем сделать это в один _шаг используя_ cargo»
стоит поменять на
489: «`./target/debug/hello_world`. Мы можем сделать это в один _шаг, используя_ cargo»

**Comment by mkpankov** [comment]
Спасибо за сообщение!

**Comment by 0niichan** [comment]
^ ^

**Comment by edubenetskiy** [comment]
Было исправлено в #36, полагаю, можно закрыть.

**Comment by mkpankov** [comment]
@edubenetskiy спасибо, закрываю!
