### ISSUE TITLE
src/method-syntax.md несоответствие текста и примера кода

### ISSUE THREAD

**Issue by Mazdaywik** [ruRust/rust_book_ru#38]
В разделе «Шаблон „Строитель“» написано:

> В противном случае, атрибуты `x` и `y` будут `0.0`, а `radius` будет `1.0`.

в то время как в коде мы имеем:

```Rust
impl CircleBuilder {
    fn new() -> CircleBuilder {
        CircleBuilder { x: 0.0, y: 0.0, radius: 0.0, }
    }
...
```
то есть радиус задан по умолчанию как `0.0`.

**Comment by edubenetskiy** [comment]
Исправлено, создан запрос на слияние #39.
