### ISSUE TITLE
src/iterators.md ошибка в переводе

### ISSUE THREAD

**Issue by Flowneee** [ruRust/rust_book_ru#49]
В разделе "Потребители" в примере с использованием `.find()`:

``` rust
let greater_than_forty_two = (0..100)
                             .find(|x| *x > 42);

match greater_than_forty_two {
    Some(_) => println!("У нас есть несколько чисел!"), // << здесь
    None => println!("Числа не найдены :("), // << и здесь
}
```

В данном случае речь идет об одном совпадении, сообщения должны быть в единственном числе или переведены дословно.

В оригинале эти сообщения выглядят так:

> "Found a match!"
> и
> "No match found :("

**Comment by atommixz** [comment]
Гораздо ближе к оригиналу было бы:
Найдено совпадение!
Совпадения не найдено :(
