### ISSUE TITLE
Добавить в словарь терминов каноничный перевод "core team"

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rust_book_ru#59]

**Comment by mkpankov** [comment]
Обсуждаем.

**Comment by shmutalov** [comment]
- Проектная группа

**Comment by QuarkDoe** [comment]
Яндекс предлагает "костяк команды", я думал про "ядро команды"
Можно ещё "основная команда".

**Comment by shmutalov** [comment]
@QuarkDoe гугл предлагает "Основная команда"

**Comment by xilec** [comment]
Вообще, на сколько я помню `lang team` несуществует, а как раз вместо нее выступает `core team` т. е. это по сути `Команда разработки языка`

**Comment by ozkriff** [comment]
context.reverso [настойчиво показывает](http://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/core+team) "основная группа"

**Comment by sumproxy** [comment]
> Вообще, на сколько я помню `lang team` несуществует, а как раз вместо нее выступает `core team` т. е. это по сути `Команда разработки языка`

Если `core team` займется например такой вещью как `Rust Platform`, то будет ли это `Команда разработки языка`?

**Comment by xilec** [comment]
@sumproxy а эта платформа будет для чего-то еще помимо самого языка Rust? Или когда `core team` переключится на разработку платформы она прекратит работу над языком и языком займется другая команда? Я лично сильно сомневаюсь в этом.

**Comment by sumproxy** [comment]
@xilec просто само сочетание `core team` не ограничивает деятельность группы только языком (это и инструменты кстати тоже), поэтому оно не такое точное в варианте `Команда разработки языка`. 
Лично я тоже за "основную группу"

**Comment by xilec** [comment]
Вообще, мне тоже нравятся варианты "основная команда" и "основная группа". И я похоже ошибся: все же есть отдельная [Language design team](https://www.rust-lang.org/en-US/team.html).

**Comment by Albibek** [comment]
Основная команда

**Comment by QuarkDoe** [comment]
IMHO "основная команда" лучший из худших. Но к сожалению хороших вариантов нет :(

**Comment by kstep** [comment]
Я за «основная команда», всё остальное хуже.

**Comment by serejkaaa512** [comment]
Вообще очень похоже на "команда разработки ядра". Если, конечно, у Rust есть ядро.

**Comment by ozkriff** [comment]
@serejkaaa512 https://doc.rust-lang.org/core/ есть, но это не про то

**Comment by mkpankov** [comment]
Как видно [тут](http://translate.academic.ru/core%20team/en/ru/) (значение перевода №2), это на самом деле термин - `основная группа (которая служит ядром) (для работы над проектом)`. А раз он уже устоялся, надо его и использовать.

Наиболее значимые обороты с этим термином будут звучать так:
* Rust Core Team decided to ... - Основная группа Rust решила ...
* Rust Core Team (в поле "автор") - Основная группа Rust
* Rust Core Team meeting - Совещание основной группы Rust

**Comment by Gordon-F** [comment]
Какой итог?

**Comment by mkpankov** [comment]
https://github.com/ruRust/rustycrate.ru/commit/0d5fb596c66bdbb446ce64eb559058d1371a69a9
