### ISSUE TITLE
Перевод "native"

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rust_book_ru#7]
Старая задача и комментарии: https://github.com/kgv/rust_book_ru/issues/189

Например, в нескольких местах есть "native libraries". "Родные библиотеки" звучит странно.

Есть что-то устоявшееся?

**Comment by Grishy** [comment]
Собственные библиотеки или нативные
Но родные больше отражают суть :smile:

**Comment by titov-andrei** [comment]
Изначальные библиотеки

**Comment by kstep** [comment]
Родные или нативные.

**Comment by Gordon-F** [comment]
Нативные библиотеки. Думаю, что это уже устоявшийся перевод.

**Comment by mkpankov** [comment]
https://github.com/ruRust/rustycrate.ru/commit/46a8a4c5a2fb5e29ea086e57116bfbce7e0f7837
