### ISSUE TITLE
Проблемы с MOBI

### ISSUE THREAD

**Issue by Lord-Protector** [ruRust/rust_book_ru#75]
На Kindle Paperwhite (и я уверен, других моделях) сам текст серый. Читать, конечно, можно, но всё же не очень удобно. При это большинство заголовкой написаны нормальным Черным цветом. Увы настроить это невозможно.
![screenshot_2017_08_06t14_29_22 0300](https://user-images.githubusercontent.com/5345489/29002832-148cee30-7ab4-11e7-9e87-f702681334b5.png)
На скриншоте контрастность выходит намного выше и это не так заметно. Но всё же отлично видно, что заголовок ярче. А в книге это выглядит особенно броско и неудобно при чтении.

Ещё не помешает обложка.

Попробую исправить сам и заслать PR.

**Comment by Lord-Protector** [comment]
Репозиторий https://github.com/mkpankov/rustbook не существует, как собрать книгу? :)

**Comment by mkpankov** [comment]
@Lord-Protector репозиторий с книгой - вот этот, где вы и создали issue: https://github.com/ruRust/rust_book_ru

**Comment by Lord-Protector** [comment]
@mkpankov у вас в этом репозитории есть скрипт `scripts/install_rustbook.sh` и он обращается к репозиторию, который я указал выше. Возможно он не нужен. В общем не хватает инструкции по сборке книжки или какого-то единого скрипта.

**Comment by mkpankov** [comment]
Восстановил репозиторий, должно заработать.

**Comment by Lord-Protector** [comment]
@mkpankov в общем решил не возится со скриптами :(
Скачал EPUB. Отредактировал его CSS. В блоке `.rustdoc` изменил `color` с `#333` на `black`. Потом конвертировал в AZW3 (дефолтный формат Kindle). И всё отлично работает, результат:
![screenshot_2017_08_07t13_56_06 0300](https://user-images.githubusercontent.com/5345489/29023942-839c12be-7b78-11e7-8cb0-56d79279ee9d.png)
Возможно кому-то пригодится:
[Rust Book.zip](https://github.com/ruRust/rust_book_ru/files/1204603/Rust.Book.zip)

**Comment by Lord-Protector** [comment]
Кстати после такого трюка с конвертациями стала отображаться обложка 👍

**Comment by mkpankov** [comment]
Хорошо, тогда закрываю
